apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: i15-1-eiger-analysis
  labels:
    workflows.diamond.ac.uk/science-group-crystallography: "true"
  annotations:
    workflows.argoproj.io/title: i15-1-eiger-analysis
    workflows.argoproj.io/description: |
      This takes a nxs filenumber and runs the processing required for the type of scan. 
      This should be done at the end of every scan.
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/crystallography-workflows"
spec:
  entrypoint: workflow-entry
  arguments:
    parameters:
      - name: filenumber
        value: "12345"
  volumes:
  - name: session
    hostPath:
      path: "{{`{{ workflow.parameters.visitdir }}`}}"
      type: Directory
  - name: tmpdir
    emptyDir: {}
  templates:
    - name: i15-1-eiger-analysis
      inputs:
        parameters:
          - name: filenumber
      script:
        image: ghcr.io/diamondlightsource/xrpd-toolbox:latest
        volumeMounts:
        - name: tmpdir
          mountPath: /tmp
        - name: session
          mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
        command: ["python"]
        env:
          - name: MKL_NUM_THREADS
            value: "1"
          - name: NUMEXPR_NUM_THREADS
            value: "1"
          - name: OMP_NUM_THREADS
            value: "1"
        source: |

          import shutil

          from xrpd_toolbox.i15_1.eiger_analysis import run_eiger_analysis
          from pathlib import Path

          import matplotlib
          matplotlib.use("Agg")
          import matplotlib.pyplot as plt
          import numpy as np

          filenumber_str = str("{{`{{ inputs.parameters.filenumber }}`}}")
          visit_dir = "{{`{{ workflow.parameters.visitdir }}`}}"

          beamline = "i15-1"
          filename = beamline + "-" + filenumber_str + ".nxs"

          nexus_filepath = Path(visit_dir) / filename

          output_xy = run_eiger_analysis(nexus_filepath=str(nexus_filepath))

          output_name = beamline + "-" + filenumber_str

          if output_xy is not None:
              xy_artifact_path = f"/tmp/{output_name}.xy"
              shutil.copy(str(output_xy), xy_artifact_path)

              try:
                two_theta, intensity = np.loadtxt(str(output_xy), unpack=True)

                artifact_path = f"/tmp/{output_name}.png"
                plt.figure()
                plt.plot(two_theta, intensity)
                plt.xlabel("2theta (deg)")
                plt.ylabel("Intensity (Arb. Units)")
                plt.title(output_name)
                plt.savefig(artifact_path)
                plt.close()
              except Exception as e:
                print(f"output_xy is not xy? :, {e} skipping plot")
          else:
              print("output_xy is None, skipping plot")


      outputs:
        artifacts:
          - name: eiger-analysis-plot
            path: "/tmp/i15-1-{{`{{inputs.parameters.filenumber}}`}}.png"
            optional: true
            archive:
              none: {}
          - name: eiger-analysis-xy
            path: "/tmp/i15-1-{{`{{inputs.parameters.filenumber}}`}}.xy"
            optional: true
            archive:
              none: {}

      podSpecPatch: |
        containers:
        - name: main
          resources:
            requests:
              cpu: "1"
              memory: 10Gi
            limits:
              cpu: "1"
              memory: 20Gi

    - name: workflow-entry
      dag:
        tasks:
        - name: i15-1-eiger-analysis
          template: i15-1-eiger-analysis
          dependencies: []
          arguments:
            parameters:
            - name: filenumber
              value: "{{`{{workflow.parameters.filenumber}}`}}"
