apiVersion: workflows.diamond.ac.uk/v1alpha1
kind: ClusterTriggerTemplate
metadata:
  name: i15-1-trigger
  labels:
    workflows.diamond.ac.uk/source: message-bus
    workflows.diamond.ac.uk/beamline: i15-1
spec:
  eventName: i15-1-message
  workflow:
    template: i15-1-plot-frames
    triggerOnMessageType: stop
    parameters:
      - name: visitdir
        path: doc.data_session_directory
      - name: filenumber
        value: doc.filenumber